"""Set up a new MSMBuilder project

"""
# Author: Matthew Harrigan <matthew.harrigan@outlook.com>
# Contributors:
# Copyright (c) 2016, Stanford University
# All rights reserved.

from __future__ import print_function, division, absolute_import
from ..cmdline import Command

from jinja2 import Environment, PackageLoader
import os
import stat
import textwrap


def chmod_plus_x(fn):
    st = os.stat(fn)
    os.chmod(fn, st.st_mode | stat.S_IEXEC)


class SetUpProject(Command):
    _group = '0-Support'
    _concrete = True
    description = __doc__

    def __init__(self, args):
        pass

    def get_header(self):
        return "# msmbuilder autogenerated template version 1"

    def start(self):
        env = Environment(loader=PackageLoader('msmbuilder',
                                               'project_templates'))
        print(env.list_templates())
        for templ_fn in env.list_templates():
            template = env.get_template(templ_fn)
            with open(templ_fn, 'w') as f:
                f.write(template.render(
                    header=self.get_header(),
                    topology_fn='data/fs-peptide.pdb',
                    timestep=10,
                ))

            if templ_fn.endswith(".sh"):
                chmod_plus_x(templ_fn)

        print('\n'.join(textwrap.wrap(
            "Ok, I wrote out a bunch of Python files that can guide you "
            "through analyzing a system with MSMBuilder. I implore you to "
            "look at the scripts before you start blindly running them. "
            "You will likely have to change some (hyper-)parameters or "
            "filenames to match your particular project."
        )))
        print()
        print('\n'.join(textwrap.wrap(
            "More than that, however, it is important that you understand "
            "exactly what the scripts are doing. Each protein system is "
            "different, and it is up to you (the researcher) to hone in on "
            "interesting aspects. This very generic pipeline may not give "
            "you any new insight for anything but the simplest systems."
        )))
