#!/usr/bin/env python
'Hidden Markov Models of Biomolecular Dynamics'
from mixtape.cmdline import App
# the commands register themselves when they're imported
from mixtape.commands import *

app = App(name='hmsm', description=__doc__)
app.start()
