#!/usr/bin/env python
'Hidden Markov Models of Biomolecular Dynamics'
from mixtape.cmdline import App
from mixtape.cmdline import argument, Command

class Subcommand1(Command):
    #name = 'subcommandname'
    description = 'description sdsdf sffsd'
    option1 = argument('--opt', help='option one is sweet', type=int)

    def start(self, args):
        print args
        print 'start!'

def main():
    app = App(name=__name__, description=__doc__)
    app.start()




if __name__ == '__main__':
    main()
