#!/usr/bin/env python
'Mixtape commands'
from mixtape.cmdline import App, NumpydocClassCommand
# the commands register themselves when they're imported
from mixtape.commands2 import *


class MixtapeApp(App):
    def _subcommands(self):
        cmds = []
        for e in super(MixtapeApp, self)._subcommands():
            if issubclass(e, NumpydocClassCommand):
                cmds.append(e)

        # sort the commands in some arbitrary order.
        return sorted(cmds, key=lambda e : ''.join(x.__name__ for x in e.mro()))


app = MixtapeApp(name='mixtape', description=__doc__)
app.start()
